### ISSUE TITLE
[typography]: Overflow of long text in <code>, <li> tags on mobile

### ISSUE THREAD

**Issue by KelseyShi** [yuhangch/astro-theme-panda#3]
## version 版本

Node.js v21.6.1
astro v4.5.12 

## problem 问题

移动端code、li标签长文本溢出

![CleanShot 2024-04-23 at 09 41 35@2x](https://github.com/yuhangch/astro-theme-panda/assets/56479000/d5e922f2-b2cb-4559-bffb-9be38f021fbf)

## A temporary patch 临时补丁

`src/styles/index.css`内添加css代码

```css
code {
  white-space: pre-wrap !important;
}

li {
  overflow-wrap: break-word;
}
```
